### ISSUE TITLE
ClimateSense graphs enhancement

### ISSUE THREAD

**Issue by russellmilliner** [roomsense/firmware#10]
On the ClimateSense page, there are graphs of climate data.  The graphs would be much more useful if there was time data at least in the hover.

Also is there an API for accessing this data, and/or controlling how much data is stored?  Or is this data only recorded when the webpage is open?

**Comment by roomsense** [comment]
@russellmilliner Adding a time/date feature is on our list for future updates. In the meantime, you can refer to HA entities for timestamp information and automation. 

The plots on the ClimateSense page are available as long as the device is running and are overwritten every 24 hours.

**Comment by russellmilliner** [comment]
Not sure why this was marked as closed/completed.  There are no time on the graphs or any apparent changes or access to the graphs in the new firmware.
