### ISSUE TITLE
Random disconnects from Wifi

### ISSUE THREAD

**Issue by djd422** [roomsense/firmware#17]
I've got two Roomsense devices. After a seemingly random number of hours, the leds start flashing orange, sensors are no longer updated in Home Assistant, and the web interface is not accessible. My access point reports that both devices have disconnected from the WiFi network. Both devices have static IP addresses.

Connecting to the web interface via the hotspot resolves the issue.

Here is a snippet of the connection log from the access point:
![image](https://github.com/user-attachments/assets/d945082c-256f-45fd-80a5-d522aaa2423f)

**Comment by roomsense** [comment]
So are they working now? 
Since you set them to static IP could you ensure there is no IP confliction?

**Comment by djd422** [comment]
No, but they remained connected for 3 days, which is the longest they've remained connected. There is no IP address conflict. "Today" in the log = 9/30/2024

![image](https://github.com/user-attachments/assets/addcf230-9290-4744-94ad-2a6c8ab9eff0)

**Comment by david-sasy** [comment]
I'm experiencing something similar and I'm wondering if it could be one of two things:

- Does it support 802.11r (Fast Roaming) ?
- Does it default to a minimum data rate below 11Mbits?
- Does it support WPA3 or WPA2 with PMF?

With UniFi systems like @djd422 has, as do we, the first two of those settings can be used to ensure stubborn client devices roam to the closest AP. If it doesn't support WPA3 or WPA2+PMF then it could also impact connection stability. Our system is currently configured for 11Mbit minimum, 802.11r enabled, and WPA2/3 with optional PMF.

When they drop off the network, they're not flashing blue/orange. Just flashing blue.

Once they've dropped off, I can get them to reconnect by connecting to the built-in AP and re-entering the WiFi details.

**Comment by roomsense** [comment]
@david-sasy, here are my commnets to your questions:

- The IQ device does not natively support 802.11r (Fast Roaming).
- By default, the RM IQ does not enforce a minimum data rate below 11 Mbits. However, the device is capable of transmitting at lower rates, such as 1 Mbps, 2 Mbps, 5.5 Mbps, and 11 Mbps, in the 802.11b mode, depending on network conditions and distance from the access point.
- It supports WPA3

Flashing blue is supposed to show that the MQTT broker disconnected not wifi unless it goes to an unknown state that we have not been able to reproduce yet.

**Comment by david-sasy** [comment]
> * The IQ device does not natively support 802.11r (Fast Roaming).

I will disable 802.11r after hours tonight and see if that makes a difference.

> Flashing blue is supposed to show that the MQTT broker disconnected not wifi unless it goes to an unknown state that we have not been able to reproduce yet.

Would you like me to start a new issue regarding this? If so, is there a way I can collect debug information to include in that? The symptoms are:
- UniFi controller logs show the RoomSenseIQ has disconnected from WiFi
- LED is flashing blue (not blue/orange)
- Power cycle will reconnect
- Can reconnect without power cycle if connecting to the RoomSense's AP and setting the WiFi details again.

Currently have it set to DHCP but have a reservation so there won't be an IP confict.

**Comment by djd422** [comment]
I'm still experiencing this issue. Fast roaming is disabled on the AP, 11Mbit minimum, and WPA2/3 with optional PMF.
