### ISSUE TITLE
Updating Firmware Issue

### ISSUE THREAD

**Issue by drone-01** [roomsense/firmware#20]
I believe I'm running into an issue while attempting to update the firmware.

Firmware Update

Latest Firmware: Jul 25 2024 - 15:20:36
  
File: roomsense-web20240903.bin
Size: 301261 bytes

!!! Upload Error !!!

**Comment by roomsense** [comment]
Hello

The displayed file size is incorrect. The firmware binary should be 1.38MB. Please download the latest version of the file [here](https://github.com/roomsense/firmware/tree/main/latest).

**Comment by drone-01** [comment]
Thanks, just downloading the BIN was the issue... I pecked around and did a "Download RAW file" and it was the correct size and the update ultimately worked as expected.
