### ISSUE TITLE
RoomSenseIQ stops functioning after 2024.08.23 FW update

### ISSUE THREAD

**Issue by mnejmantowicz** [roomsense/firmware#5]
I configured my device on the pre-installed FW. Everything was working fine. Then I updated to the latest version. The update completed successfully and then after several hours the device disconnected from he WiFi and the light is solid orange.

Can we please have instructions on how to re-flash the ESP32S3?

**Comment by mnejmantowicz** [comment]
**_Looks like the unit is stuck in a reboot loop:_**

ESP-ROM:esp32s3-20210327

Build:Mar 27 2021

rst:0xc (RTC_SW_CPU_RST),boot:0x2b (SPI_FAST_FLASH_BOOT)

Saved PC:0x40375c0c

SPIWP:0xee

mode:DIO, clock div:1

load:0x3fce3808,len:0x1674

load:0x403c9700,len:0xbb8

load:0x403cc700,len:0x2e8c

entry 0x403c9954

[0;32mI (29) boot: ESP-IDF v4.4.3-2-ge1510f3354-dirty 2nd stage bootloader[0m

[0;32mI (29) boot: compile time 14:22:00[0m

[0;32mI (29) boot: chip revision: 0[0m

[0;32mI (33) boot.esp32s3: Boot SPI Speed : 80MHz[0m

[0;32mI (37) boot.esp32s3: SPI Mode       : DIO[0m

[0;32mI (42) boot.esp32s3: SPI Flash Size : 8MB[0m

[0;32mI (47) boot: Enabling RNG early entropy source...[0m

[0;32mI (52) boot: Partition Table:[0m

[0;32mI (56) boot: ## Label            Usage          Type ST Offset   Length[0m

[0;32mI (63) boot:  0 nvs              WiFi data        01 02 00009000 00004000[0m

[0;32mI (71) boot:  1 otadata          OTA data         01 00 0000d000 00002000[0m

[0;32mI (78) boot:  2 phy_init         RF data          01 01 0000f000 00001000[0m

[0;32mI (85) boot:  3 ota_0            OTA app          00 10 00010000 00300000[0m

[0;32mI (93) boot:  4 ota_1            OTA app          00 11 00310000 00300000[0m

[0;32mI (100) boot: End of partition table[0m

[0;32mI (105) esp_image: segment 0: paddr=00310020 vaddr=3c0b0020 size=a1c54h (662612) map[0m

[0;32mI (232) esp_image: segment 1: paddr=003b1c7c vaddr=3fc9a480 size=05080h ( 20608) load[0m

[0;32mI (237) esp_image: segment 2: paddr=003b6d04 vaddr=40374000 size=09314h ( 37652) load[0m

[0;32mI (246) esp_image: segment 3: paddr=003c0020 vaddr=42000020 size=a216ch (663916) map[0m

[0;32mI (366) esp_image: segment 4: paddr=00462194 vaddr=4037d314 size=0d160h ( 53600) load[0m

[0;32mI (378) esp_image: segment 5: paddr=0046f2fc vaddr=50000000 size=00010h (    16) load[0m

[0;32mI (387) boot: Loaded app from partition at offset 0x310000[0m

[0;32mI (387) boot: Disabling RNG early entropy source...[0m

[0;32mI (399) cpu_start: Pro cpu up.[0m

[0;32mI (399) cpu_start: Starting app cpu, entry point is 0x40375654[0m

[0;32mI (377) cpu_start: App cpu up.[0m

[0;32mI (413) cpu_start: Pro cpu start user code[0m

[0;32mI (413) cpu_start: cpu freq: 160000000[0m

[0;32mI (413) cpu_start: Application information:[0m

[0;32mI (416) cpu_start: Project name:     roomsense-web[0m

[0;32mI (421) cpu_start: App version:      757eb66-dirty[0m

[0;32mI (427) cpu_start: Compile time:     Aug 23 2024 13:23:36[0m

[0;32mI (433) cpu_start: ELF file SHA256:  18b33b8e375f65a2...[0m

[0;32mI (439) cpu_start: ESP-IDF:          v4.4.3-2-ge1510f3354-dirty[0m

[0;32mI (445) heap_init: Initializing. RAM available for dynamic allocation:[0m

[0;32mI (452) heap_init: At 3FCA6840 len 00042ED0 (267 KiB): D/IRAM[0m

[0;32mI (459) heap_init: At 3FCE9710 len 00005724 (21 KiB): STACK/DRAM[0m

[0;32mI (466) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM[0m

[0;32mI (472) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM[0m

[0;32mI (479) spi_flash: detected chip: gd[0m

[0;32mI (482) spi_flash: flash io: dio[0m

[0;32mI (487) sleep: Configure to isolate all GPIO pins in sleep state[0m

[0;32mI (493) sleep: Enable automatic switching of GPIO sleep configuration[0m

[0;32mI (500) cpu_start: Starting scheduler on PRO CPU.[0m

[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m

RoomSense © Production image version 20240806

[0;32mI (561) system_api: Base MAC address is not set[0m

[0;32mI (561) system_api: read default base MAC address from EFUSE[0m

[0;32mI (561) MAIN: MAC address: 806599A3440C[0m

[0;32mI (561) co-sensor: STARTING CO Sensor task...[0m

[0;31mE (571) i2cdev: Could not read from device [0x4d at 0]: -1 (ESP_FAIL)[0m

ESP_ERROR_CHECK_WITHOUT_ABORT failed: esp_err_t 0xffffffff (ESP_FAIL) at 0x4037dbd7

file: "./main/climatesense.c" line 337

func: climatesense_task

expression: measure_pm(&mpm, PM_ONE_REG, &data)

[0;31mE (591) climatesense: PM reading error results -1 (ESP_FAIL)[0m

[0;31mE (601) i2cdev: Could not write to device [0x62 at 0]: -1 (ESP_FAIL)[0m

ESP_ERROR_CHECK_WITHOUT_ABORT failed: esp_err_t 0xffffffff (ESP_FAIL) at 0x4037dbd7

file: "./main/climatesense.c" line 353

func: climatesense_task

expression: scd4x_stop_periodic_measurement(&(scd.i2c_dev))

[0;32mI (601) wifi_app: STARTING WIFI APPLICATION[0m

[0;31mE (621) i2cdev: Could not write to device [0x62 at 0]: -1 (ESP_FAIL)[0m

[0;32mI (641) climatesense: scd4x_perform_self_test failed.

[0m

[0;31mE (641) i2cdev: Could not write to device [0x62 at 0]: -1 (ESP_FAIL)[0m

ESP_ERROR_CHECK_WITHOUT_ABORT failed: esp_err_t 0xffffffff (ESP_FAIL) at 0x4037dbd7

file: "./main/climatesense.c" line 369

func: climatesense_task

expression: scd4x_reinit(&(scd.i2c_dev))

[0;32mI (671) pp: pp rom version: e7ae62f[0m

[0;32mI (671) net80211: net80211 rom version: e7ae62f[0m

[0;31mE (681) i2cdev: Could not write to device [0x62 at 0]: -1 (ESP_FAIL)[0m

ESP_ERROR_CHECK_WITHOUT_ABOR[0;32mI (691) wifi_init: rx ba win: 6[0m

[0;32mI (691) wifi_init: tcpip mbox: 32[0m

[0;32mI (691) wifi_init: udp mbox: 6[0m

[0;32mI (701) wifi_init: tcp mbox: 6[0m

[0;32mI (701) wifi_init: tcp tx win: 5744[0m

[0;32mI (701) wifi_init: tcp rx win: 5744[0m

[0;32mI (711) wifi_init: tcp mss: 1440[0m

[0;32mI (711) wifi_init: WiFi IRAM OP enabled[0m

[0;32mI (721) wifi_init: WiFi RX IRAM OP enabled[0m

[0;32mI (721) wifi_init: LWIP IRAM OP enabled[0m

ESP_ERROR_CHECK failed: esp_err_t 0x300b (ESP_ERR_WIFI_PASSWORD) at 0x4037dbec

file: "./main/wifi_app.c" line 235

func: wifi_app_soft_ap_config

expression: esp_wifi_set_config(ESP_IF_WIFI_AP, &ap_config)



abort() was called at PC 0x4037dbef on core 0





Backtrace: 0x40375f6e:0x3fcee270 0x4037dbf9:0x3fcee290 0x4038797a:0x3fcee2b0 0x4037dbef:0x3fcee320 0x42009571:0x3fcee340 0x4200987d:0x3fcee400 0x40380fa9:0x3fcee430









ELF file SHA256: 18b33b8e375f65a2



Rebooting...

**Comment by roomsense** [comment]
Is the issue persist after power cycle of the device? 
Are you able to connect to RoomSense access point? 

There are also some errors for ClimateSense module. Is it connected?

**Comment by mnejmantowicz** [comment]
So, the device is now in a continuous loop as you can see from the last line. Power cycling did not help. I do NOT have a ClimateSense module. I followed the instructions on your website and applied the firmware from this repo.

**Comment by tofurky** [comment]
```
ESP_ERROR_CHECK failed: esp_err_t 0x300b (ESP_ERR_WIFI_PASSWORD) at 0x4037dbec
```

It looks like it's failing to start the AP. Maybe the area in flash where the password is stored is corrupt somehow? Apparently, that same ESP_ERR_WIFI_PASSWORD can happen if it's < 8 characters somehow.

A recovery image can be flashed via esptool.py over USB serial; I haven't tried it, though: https://github.com/roomsense/firmware/tree/main/Serial%20Flasher

**Comment by mnejmantowicz** [comment]
Thank you so much!! That worked like a charm! I have a working device now.
