### ISSUE TITLE
Wifi / Firmware Issues

### ISSUE THREAD

**Issue by wh1t3f1r3** [roomsense/firmware#7]
Hello,

I'm having 2 different issues with my Roomsense and I'm hoping you can help.  The first issue is the device refuses to join my Wifi network(s).  The network I'm attempting to join is running WPA2-PSK with the option for CCMP, CCMP256, GCMP & GCMP256 encryption.  Can you tell me if the Roomsense only support TKIP encryption?

The second and slightly more concerning issue has to do with firmware updates.  I've downloaded roomsense-web20240823.bin (MD5 4db4f5d03e28b027834a4ad8ce312760) and I've attempted to apply the update 3x times. After every reboot the device still shows that it is running a firmware from 8/12/2024 (firmware the device shipped with).  Screenshots below will show the before and after.

**Before Firmware Update:**
<img width="460" alt="Screenshot 2024-08-29 at 10 38 50 AM" src="https://github.com/user-attachments/assets/fb997e22-dcbe-4a9a-8cef-1ea3c6ceadf3">

**Firmware Selected for Upload**
<img width="411" alt="Screenshot 2024-08-29 at 10 39 06 AM" src="https://github.com/user-attachments/assets/6f7a50fd-6048-450a-b451-0968eab79614">

**Firmware Update in Progres**
<img width="615" alt="Screenshot 2024-08-29 at 10 39 14 AM" src="https://github.com/user-attachments/assets/2753aca1-db42-47af-81e6-3171e3ee58df">

**Firmware Update Complete & device rebooting**
<img width="640" alt="Screenshot 2024-08-29 at 10 39 27 AM" src="https://github.com/user-attachments/assets/b2071203-1c33-498b-bf9d-4d965f44cab2">

**After Firmware Update**
<img width="381" alt="Screenshot 2024-08-29 at 10 39 55 AM" src="https://github.com/user-attachments/assets/0951098f-0d12-4c39-90eb-92ba3f8aa457">

Let me know if you need any additional information.

**Comment by russellmilliner** [comment]
I believe the Aug 12 is the date in that firmware file.  My orig firmware was from May, but after doing that 0823 file, it changed to Aug 12, so it sounds like you're on the latest.

**Comment by russellmilliner** [comment]
I think you (RoomSense) would save yourself significant trouble if you setup some kind of firmware check/update right from the device, or since many are integrating with HomeAssistant, have HomeAssistant or ESPHome perform the firmware upgrade.  I am not sure if they is capable with MQTT devices.

**Comment by roomsense** [comment]
The binary file includes the creation date and will be updated with each new firmware release.

**Comment by wh1t3f1r3** [comment]
As a follow up on this.  I agree that it would be a nice feature to have the device check for the firmware directly or at the very least have the firmware date in the WebUI match the date on the file that is published.


I have also solved the wifi issue.  I had to disable CCMP256 and GCMP256 encryption on the SSID I put my home automation devices on.  This tells me that there is an issue in the encryption negotiation between the Roomsense and my Access Point.  I have probably 10 other ESP32 devices on the same network that don't have this issue so hopefully this is a software issue that can be fixed in a future firmware update.

**Comment by roomsense** [comment]
@wh1t3f1r3 The firmware date will be updated in the upcoming release.  

RoomSense uses the WPA2-PSK security protocol. I believe setting your router to support this protocol should resolve the issue.

**Comment by wh1t3f1r3** [comment]
@roomsense  - All I'm using and discussing is WPA2-PSK.  The CCMP / GCMP are wireless encryption protocols that are part of the 802.11 standard.  Specifically starting with 802.11ac is when the GCMP encryption protocol was introduced.  What should happen is since my Access Point was advertising 4 different encryption protocols (CCMP / CCMP256 / GCMP / GCMP256), if the device can't use CCMP256 or GCMP256 it should fail back to CCMP or GCMP (if the ESP32 chip support GCMP) during the negotiation process.  That failing back isn't happen when I have CCMP256 & GCMP256 enabled.  As I mentioned previously I've disabled the CCMP256 and GCMP256 encryption protocol so everything is working for me.  I was just calling out this issues so hopefully it could be addressed in a future firmware release.
